save_dir: ./cifar100
save_name: debiased_cifar100_lt_30_50_1
resume: False
load_path: None
overwrite: True
use_tensorboard: True
epoch: 1
num_train_iter: 393216
num_eval_iter: 1000
num_labels: 400
batch_size: 64
eval_batch_size: 1024
hard_label: True
T: 0.5
p_cutoff: 0.95
ulb_loss_ratio: 1.0
uratio: 7
ema_m: 0.999
optim: SGD
lr: 0.03
momentum: 0.9
weight_decay: 0.001
amp: False
net: WideResNet
net_from_name: False
depth: 28
widen_factor: 8
leaky_slope: 0.1
dropout: 0.0
data_dir: ./data
dataset: cifar100
train_sampler: RandomSampler
num_classes: 100
num_workers: 4
alg: fixmatch
seed: 1
world_size: 1
rank: 0
multiprocessing_distributed: False
dist_url: tcp://127.0.0.1:10007
dist_backend: nccl
gpu: 0
cycle: 0
long_tail: True
imb_ratio_lb: 50
imb_ratio_ulb: 50
labeled_percentage: 30
tau: 0.5
use_energy: False
e_cutoff: -11.0
use_debias: True
use_marginal_loss: True
